using Godot;
using System;

public partial class IdleKnight : Node2D
{
  
    // Called when the node enters the scene tree for the first time.
    public string knightColor { get; private set; }
    public void setKnight(string color, AnimatedSprite2D knight)
    {
        // ✅ 1. Choose which knight you want
        // Change to "Red" for red knight
        knightColor = color;
        string spritePath = $"res://Assets/Tiny Swords (Free Pack)/Units/{knightColor} Units/Warrior/Warrior_Idle.png";

        // 2️⃣ Load sprite sheet texture
        Texture2D spriteSheet = GD.Load<Texture2D>(spritePath);

        // 3️⃣ Create SpriteFrames resource
        var spriteFrames = new SpriteFrames();

        // 4️⃣ Add animation
        string animationName = "idle";
        spriteFrames.AddAnimation(animationName);
        spriteFrames.SetAnimationSpeed(animationName, 10);

        // 5️⃣ Calculate frame size
        int horizontalFrames = 8;
        int frameWidth = spriteSheet.GetWidth() / horizontalFrames;
        int frameHeight = spriteSheet.GetHeight();

        // 6️⃣ Slice sprite sheet manually
        for (int i = 0; i < horizontalFrames; i++)
        {
            var atlasTexture = new AtlasTexture();
            atlasTexture.Atlas = spriteSheet;
            atlasTexture.Region = new Rect2(
                i * frameWidth,
                0,
                frameWidth,
                frameHeight
            );

            spriteFrames.AddFrame(animationName, atlasTexture);
        }

        // 7️⃣ Assign SpriteFrames
        knight.SpriteFrames = spriteFrames;

        // 8️⃣ Play animation
        
        knight.Scale = new Vector2(0.7f, 0.7f);
        if (knightColor == "Black")
        {
            knight.Modulate = new Color(1, 1, 1, 0.7f);
        }
        else
        {
            knight.Play(animationName);
            knight.Modulate = new Color(1, 1, 1, 1f); 
        }
    }

    public void SetOutline(AnimatedSprite2D knight, bool enabled)
    {
        if (enabled)
        {
            // Create a new ShaderMaterial
            var material = new ShaderMaterial();
            material.Shader = GD.Load<Shader>("res://Shader/outline.gdshader");

            // Set outline parameters
            material.SetShaderParameter("outline_color", new Color(1, 1, 0)); // default yellow
            material.SetShaderParameter("outline_size", 2.0f);

            // Apply material to sprite
            knight.Material = material;
        }
        else
        {
            // Remove the outline by clearing the material
            knight.Material = null;
        }
    }
    
    // this function was generated by ChatGPT
    public void PlayDustEffect(Vector2 position)
    {
        // 1️⃣ Create the dust AnimatedSprite2D
        var dust = new AnimatedSprite2D();
        dust.ZIndex = 5; 
        // 2️⃣ Load the sprite sheet texture
        string dustPath = "res://Assets/Tiny Swords (Free Pack)/Particle FX/Dust_02.png"; // your 10-frame dust sprite sheet
        Texture2D dustSheet = GD.Load<Texture2D>(dustPath);

        // 3️⃣ Create SpriteFrames for the dust animation
        var spriteFrames = new SpriteFrames();
        string animationName = "dust";
        spriteFrames.AddAnimation(animationName);
        spriteFrames.SetAnimationSpeed(animationName, 10); // frames per second

        int frames = 10; // your dust animation frames
        int frameWidth = dustSheet.GetWidth() / frames;
        int frameHeight = dustSheet.GetHeight();

        for (int i = 0; i < frames; i++)
        {
            var atlasTexture = new AtlasTexture();
            atlasTexture.Atlas = dustSheet;
            atlasTexture.Region = new Rect2(i * frameWidth, 0, frameWidth, frameHeight);
            spriteFrames.AddFrame(animationName, atlasTexture);
        }

        dust.SpriteFrames = spriteFrames;
        dust.Animation = animationName;
        dust.Position = position;
        dust.Scale = new Vector2(1.0f, 1.0f); // adjust size if needed
        dust.Play(animationName);

        // 4️⃣ Ensure dust is visible even if knight is hidden
        dust.Visible = true;

        // 5️⃣ Optional: detach from knight so hiding the knight won't hide the dust
        GetParent().AddChild(dust); // parent to the same Node2D that holds the knight
        dust.GlobalPosition = this.GlobalPosition + position; // place above knight

        // 6️⃣ Queue free after animation finishes
        float animationDuration = frames / 15.0f; // frames / fps
        Timer timer = new Timer();
        timer.WaitTime = animationDuration;
        timer.OneShot = true;
        timer.Timeout += () => dust.QueueFree(); // remove dust after playing
        AddChild(timer);
        timer.Start();
    }
    public override void _Ready()
    {
        var animatedSprite = new AnimatedSprite2D();
        AddChild(animatedSprite);

        setKnight("Blue", animatedSprite);
        
    }

    // Called every frame. 'delta' is the elapsed time since the previous frame.
    public override void _Process(double delta)
    {
    }
}
